[build]
  publish = "publish"
  functions = "functions-zip"

[[plugins]]
  package = "./plugins/isg"

[[redirects]]
  from = "/storefront.*"
  to = "/storefront.js"
  status = 200

[[redirects]]
  from = "/checkout.*"
  to = "/checkout.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200

[[headers]]
  for = "/storefront.*"
  [headers.values]
  	Cache-Control = "public, max-age=600, s-maxage=60, must-revalidate"

[[headers]]
  for = "/checkout.*"
  [headers.values]
  	Cache-Control = "public, max-age=600, s-maxage=60"

[[headers]]
  for = "/img/*"
  [headers.values]
  	Cache-Control = "public, max-age=300, s-maxage=60, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
  	Cache-Control = "public, max-age=86400, s-maxage=600"
