[build]
  command = "echo 'E-Com Plus Storefront ISG'"
  publish = "publish"
  functions = "functions"
  NODE_ENV = "10.15.3"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200
