- name: 'pages'
    label: 'Pages'
    delete: false
    files:
      - name: 'home'
        label: 'Homepage'
        file: 'content/pages/home.json'
        fields:
          - {label: 'Título', name: 'title', widget: 'string', hint: "É relevante para SEO e exibida na aba do navegador"}
          - label: "Slider"
            name: "carousel"
            widget: object
            fields:
              - label: Slides
                name: slides
                widget: list
                fields:
                  - {label: Imagem, name: image, widget: image}
                  - {label: Link, required: false, name: link, widget: string}
          - name: 'showcase'
            label: 'Vitrine'
            widget: object
            fields:
              - label: Coleções
                name: colections
                widget: list
                hint: "Lista de coleções exibidas na vitrine"
                fields:
                  - {label: Link, required: false, name: link, widget: string, hint: "Entrar com o ID da coleção, que pode ser visto nesta página: https://app.e-com.plus/#/resources/collections"}
          - label: "Info banner"
            name: "info_banner"
            widget: object
            fields:
              - {label: Frete, required: false, name: shipping, widget: string}
              - {label: Parcelamento, required: false, name: installment, widget: string}
              - {label: Trocas, required: false, name: exchange, widget: string}
              - {label: Promoção, required: false, name: promo, widget: string}
