backend:
  name: git-gateway
  branch: master

media_folder: 'public/img/uploads'
public_folder: '/img/uploads'

collections:

  # static content for pages
  # may vary by template
  - name: 'pages'
    label: 'Pages'
    delete: false
    files:
      - name: 'home'
        label: 'Homepage'
        file: 'content/pages/home.json'
        fields:
          - {label: 'Name', name: 'name', widget: 'string'}

  # default blog posts collection
  # remove if your template does not support blog
  - name: 'blog_posts'
    label: 'Blog Posts'
    description: 'Add extra content to the site with blog posts related to your store and clients'
    folder: 'content/blog-posts'
    extension: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', name: 'thumbnail', widget: 'image'}
      - {label: 'Short Description', name: 'description', widget: 'text'}
      - {label: 'Body', name: 'body', widget: 'markdown'}

  # default extra pages collection
  # eg.: 'about us', 'contact' and 'privacy'
  - name: 'extra_pages'
    label: 'Extra Pages'
    description: 'Add extra content to the site with blog posts related to your store and clients'
    folder: 'content/extra-pages'
    extension: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', name: 'thumbnail', widget: 'image'}
      - {label: 'Short Description', name: 'description', widget: 'text'}
      - {label: 'Body', name: 'body', widget: 'markdown'}

  # general site settings
  # usually will be the same for any template
  - name: 'settings'
    label: 'Settings'
    description: 'General settings to modify the site identity and metadata'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'content/settings.json'
        fields:
          - {label: 'Name', name: 'name', widget: 'string'}
          - {label: 'Short Name', name: 'short_name', widget: 'string'}
          - {label: 'Short Description', name: 'description', widget: 'text'}
          - {label: 'Language', name: 'lang', widget: 'string'}
          - {label: 'Store ID', name: 'store_id', widget: 'number'}
          - {label: 'Store Object ID', name: 'store_object_id', widget: 'string'}
          - {label: 'Logo', name: 'logo', widget: 'image', required: false}
          - {label: 'Mini Logo', name: 'mini_logo', widget: 'image', required: false}
          - {label: 'Primary Color', name: 'primary_color', widget: 'string'}
          - {label: 'Secondary Color', name: 'secondary_color', widget: 'string'}
          - {label: 'App Background Color', name: 'bg_color', widget: 'string'}
          - {label: 'Icon', name: 'icon', widget: 'image'}
          - {label: 'Large Icon', name: 'large_icon', widget: 'image'}
          - {label: 'Favicon', name: 'favicon', widget: 'image'}

  # Site Layout
  # usually will be applied all pages
  - name: 'layout'
    label: 'Layout'
    description: 'Layout applied to all pages'
    delete: false
    editor:
      preview: false
    files:
      - name: 'header'
        label: 'Header'
        file: 'content/layout/header.json'
        fields:
          - label: "Tarja de marketing "
            name: "marketing_stripe"
            widget: object
            hint: "Tarja na cor secundária com texto e botão, caso não seja configurada não é exibida na loja"
            fields:
              - {label: 'Texto', name: 'text', required: false, widget: 'string'}
              - {label: 'Texto do botão', name: 'call_to_action', required: false, widget: 'string'}
              - {label: 'Link do botão', name: 'call_to_action_link', required: false, widget: 'string'}
          - label: "Tarja de contatos"
            name: "contacts_stripe"
            widget: object
            hint: "Tarja com contatos da loja, como páginas internas, telefones e redes sociais"
            fields:
              - label: Páginas
                name: pages
                widget: list
                fields:
                  - {label: Título, name: title, required: false, widget: string}
                  - {label: Link, name: link, required: false, widget: string}
              - {label: 'Telefone', name: 'phone', required: false, widget: 'string'}
              - {label: 'Whatsapp', name: 'whatsapp', required: false, widget: 'string'}
              - name: 'social_links'
                widget: object
                hint: "Entrar com a url da página nas devidas redes sociais"
                label: 'Links para redes sociais'
                fields:
                  - {label: 'Facebook', name: 'facebook', widget: 'string', required: false}
                  - {label: 'Twitter', name: 'twitter', widget: 'string', required: false}
                  - {label: 'Youtube', name: 'youtube', widget: 'string', required: false}
                  - {label: 'Instagram', name: 'instagram', widget: 'string', required: false}
                  - {label: 'Pinterest', name: 'pinterest', widget: 'string', required: false}

      - name: 'footer'
        label: 'Footer'
        file: 'content/layout/footer.json'
        fields:
          - label: Descrição
            name: description
            widget: object
            fields:
              - {label: Título, hint: "Em destaque, dentro de uma tag H2", required: false, name: title, widget: string}
              - {label: Texto, required: false, name: body, widget: markdown}
          - label: Lista de links 1
            name: link_list_1
            widget: object
            hint: "Lista de links normalmente utilizada para exibir páginas como, Sobre nós e Política de privacidade"
            fields:
              - {label: "Listar páginas", hint: "Ativar para listar as páginas extra automáticamente", name: "list_pages", widget: "boolean", default: true}
              - {label: Título, required: false, name: title, widget: string}
              - label: Links
                name: links
                widget: list
                fields:
                  - {label: Texto, required: false, name: text, widget: string}
                  - {label: URL, required: false, name: url, widget: string}
          - label: Lista de links 2
            name: link_list_2
            widget: object
            hint: "Lista adicional de links, para exibir páginas"
            fields:
              - {label: "Listar categorias", hint: "Ativar para listar as categorias da loja automáticamente", name: "list_categories", widget: "boolean", default: true}
              - {label: Título, required: false, name: title, widget: string}
              - label: Links
                name: links
                widget: list
                fields:
                  - {label: Texto, required: false, name: text, widget: string}
                  - {label: URL, required: false, name: url, widget: string}
          - label: Contatos
            name: contacts
            widget: object
            hint: "Contatos da loja"
            fields:
              - {label: 'Título', required: false, name: title, widget: string}
              - {label: 'Telefone', required: false, name: phone, widget: string}
              - {label: 'email', required: false, name: email, widget: string}
              - {label: 'Whatsapp', required: false, name: whatsapp, widget: string}
              - {label: 'Facebook', name: 'facebook', widget: 'string', required: false}
              - {label: 'Twitter', name: 'twitter', widget: 'string', required: false}
              - {label: 'Youtube', name: 'youtube', widget: 'string', required: false}
              - {label: 'Instagram', name: 'instagram', widget: 'string', required: false}
              - {label: 'Pinterest', name: 'pinterest', widget: 'string', required: false}
          - label: Selos
            name: seals
            widget: list
            fields:
              - {label: Imagem, required: false, name: image, widget: image}
              - {label: alt, required: false, name: Alt tag, widget: string}
          - label: 'Meios de pagamento'
            name: 'payment_methods'
            widget: 'object'
            fields:
              - {label: "Boleto", name: "boleto", widget: "boolean", default: true, required: false}
              - {label: "Visa", name: "visa", widget: "boolean", default: true, required: false}
              - {label: "Mastercard", name: "mastercard", widget: "boolean", default: true, required: false}
              - {label: "Elo", name: "elo", widget: "boolean", default: true, required: false}
              - {label: "American Express", name: "amex", widget: "boolean", default: true, required: false}
              - {label: "Hipercard", name: "hipercard", widget: "boolean", default: true, required: false}
              - {label: "Hiper", name: "hiper", widget: "boolean", default: true, required: false}
              - {label: "Diners", name: "diners", widget: "boolean", default: true, required: false}
              - {label: "Aura", name: "aura", widget: "boolean", default: true, required: false}
              - {label: "Itaú", name: "itau", widget: "boolean", default: true, required: false}
              - {label: "Bradesco", name: "bradesco", widget: "boolean", default: true, required: false}
              - {label: "Banco do Brasil", name: "bb", widget: "boolean", default: true, required: false}
              - {label: "Santander", name: "santander", widget: "boolean", default: true, required: false}
              - {label: "Citibank", name: "citibank", widget: "boolean", default: true, required: false}
              - {label: "HSBC", name: "hsbc", widget: "boolean", default: true, required: false}
              - {label: "Banrisul", name: "banrisul", widget: "boolean", default: true, required: false}
              - {label: "Mais", name: "mais", widget: "Mais", default: true, required: false}
          - label: Creditos
            name: credits
            widget: object
            fields:
              - {label: Texto, required: false, name: texto, widget: string}
