name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    name: Automerge PR
    runs-on: ubuntu-latest
    if: github.actor == "leomp12" || github.actor == "app/dependabot-preview"
    steps:
      - name: leomp12/automerge-action
        uses: leomp12/automerge-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: automerge
