name: Build and deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - name: JamesIves/github-pages-deploy-action@releases
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: dist
