name: Update views

on:
  schedule:
    - cron: '50 18 * * MON-FRI'
  push:
    branches:
      - master
    paths:
      - '.github/update-views'
  pull_request:
    paths:
      - 'package.json'

jobs:
  update-views:
    name: Update default EJS views
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Config Git user
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'

      - name: Pull views subtree
        continue-on-error: true
        run: |
          git subtree pull --prefix=template/pages --message="Merge views subtree" \
            https://github.com/ecomplus/storefront-starter-views master --squash

      - name: Checkout diff as ours
        run: |
          for file in ./template/pages/**
          do
            git checkout --ours $file -q
          done

      - name: Check file changes
        run: |
          git add template/pages
          (git diff-index --quiet HEAD && echo "::set-output name=diff::0") || echo "::set-output name=diff::1"
        id: git_diff

      - name: Commit template pages
        if: steps.git_diff.outputs.diff == 1
        run: |
          git commit -m "fix(pages): update/merge default views"

      - name: Extract branch name
        if: steps.git_diff.outputs.diff == 1
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push changes
        if: steps.git_diff.outputs.diff == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
